add av feedstock
open-ce/open-ce pull request #69
Opened 2020-10-01 16:29 UTC by cdeepali

## Checklist before submitting

- [ ] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/master/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/master/doc/)?
- [ ] Did you write any [tests](https://github.com/open-ce/open-ce/blob/master/tests/) to validate this change?  

## Description

Fixes # (issue).

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) requests changes, they must be addressed.

2020-10-06 12:23 UTC, npanpaliya approved these changes

2020-10-06 18:34 UTC, dncliss approved these changes

2020-10-07 13:07 UTC, dncliss approved these changes

2020-10-07 18:41 UTC, jayfurmanek approved these changes
Looks good. We can rerun the linter once we push in the av feedstock.

2020-10-07 21:29 UTC, jayfurmanek requested changes
Actually upon further review, let's loosen the pyav pin. According to https://github.com/PyAV-Org/PyAV/blob/main/CHANGELOG.rst  pyAv uses semantic versioning, which says:

```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```

So as long as they stay true to that we can change this pin to `8.*`

2020-10-09 13:50 UTC, bnemanich approved these changes

2020-10-12 17:45 UTC, cdeepali commented
@jayfurmanek, I have updated the `{av}` pin as suggested.

2020-10-12 17:54 UTC, jayfurmanek approved these changes

2020-10-13 04:41 UTC, merged